---
title             : "The title"
shorttitle        : "Title"

author: 
  - name          : "First Author"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "my@email.com"
    role:         # Contributorship roles (e.g., CRediT, https://casrai.org/credit/)
      - "Conceptualization"
      - "Writing - Original Draft Preparation"
      - "Writing - Review & Editing"
  - name          : "Ernst-August Doelle"
    affiliation   : "1,2"
    role:
      - "Writing - Review & Editing"
      - "Supervision"

affiliation:
  - id            : "1"
    institution   : "Wilhelm-Wundt-University"
  - id            : "2"
    institution   : "Konstanz Business School"

authornote: |
  Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

  Enter author note here.

abstract: |
  We are using this SIOP submission as the main place we try to get from 20 to 18 items. This will later be incorporated into the larger paper as well as the tech report.
  
keywords          : "keywords"
wordcount         : "X"

bibliography      : ["r-references.bib", "scale_reduction.bib"]

floatsintext      : no
linenumbers       : yes
draft             : no
mask              : no

figurelist        : no
tablelist         : no
footnotelist      : no

classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library("papaja")
r_refs("r-references.bib")
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```

```{r  grabdata}

data <- read.csv("Engagement+(post-Qualtrics)_May+17,+2022_11.10.csv")[-c(1:2),]


```

This is the paper that gets us from 20 items down to the desired 18. We did NOT consult with @freud2012basic for any analyses!!!

# Methods
CFA modification indices and corrected item-total correlations

## Participants

Our sample size is `r nrow(data)`

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References

::: {#refs custom-style="Bibliography"}
:::
